### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by iatsdotfatr** [MadGoby/Task-2#2]
1. Архитектура bem с официального сайта используется при работе с css, без шаблонов. В папке с бэм-блоком должен находится один шаблон (pug) блока со всеми его элементами и модификаторами и один scss-файл, в котором описываются стили только этого блока со всеми его элементами и модификаторами. Один файл = один блок, никаких файлов с элементами и модификаторами.
![Screenshot from 2021-07-22 20-48-36](https://user-images.githubusercontent.com/51824674/126661630-31f13e44-bdcc-4fc1-8ec5-d3dd223c2372.png)

2. Сделать папку для страниц, и для каждой отдельной страницы. Страницы оформить точно также, как и другие блоки.

**Comment by iatsdotfatr** [comment]
В одном pug-файле должен находится один миксин, который соответствует бэм-блоку. Один миксин в файле, и миксинов-элементов быть не должно.

Вместо этого, деструктурируй параметры миксина и задай им значения по умолчанию.
![Screenshot from 2021-07-29 19-12-53](https://user-images.githubusercontent.com/51824674/127498298-8e51bb9b-00b3-4a42-874b-ac6e557558df.png)

**Comment by DmitrijMTP** [comment]
Деструкторизации не появилось. Вместо того, чтобы писать список переменных, это можно сделать короче
![2021-08-30_17-54](https://user-images.githubusercontent.com/85491485/131359162-f28a41ff-3238-4251-9382-85c61f7e0462.png)
И сразу же уйдет куча if'ов ниже

**Comment by DmitrijMTP** [comment]
Если в дальнейшем переменная не мутируется, то нужно использовать const

Не очень понятный момент: на примере компонента "button". Он вызывается таким образом везде 
![2021-09-13_18-34](https://user-images.githubusercontent.com/85491485/133113332-7c8b3c90-138d-4f7a-9753-7ccd29fa8408.png)
Для чего создается дополнительная переменная, можно же напрямую использовать "attr,type" и т.д.?
![2021-09-13_18-36](https://user-images.githubusercontent.com/85491485/133113748-1d3c488f-e343-4e07-b03d-f36596d7e140.png)

**Comment by DmitrijMTP** [comment]
Почему-то ui-kit отдельно выделен, если это не страницы отдельные, то они должны быть в блоках и оформлены в виде миксинов, если страницы то в pages
![2021-09-13_19-17](https://user-images.githubusercontent.com/85491485/133120282-64029dc2-c173-461d-8e48-51482533a998.png)

**Comment by DmitrijMTP** [comment]
Можно закрывать
