### ISSUE TITLE
Common

### ISSUE THREAD

**Issue by iatsdotfatr** [MadGoby/Task-2#3]
Убрать dist в gitignore, если нужна для gh-pages, создать под нее отдельную ветку.
![gitignore](https://user-images.githubusercontent.com/51824674/126662671-8cd13643-8504-42c3-8938-7b997b905910.png)

**Comment by iatsdotfatr** [comment]
1. Установить eslint с конфигами air-bnb и eslint-plugin-fsd и установить и настроить prettier. После этого внести правки в js-файлы, и отформатировать scss-файлы, чтобы вот из такого:
![Screenshot from 2021-07-29 19-01-54](https://user-images.githubusercontent.com/51824674/127499431-efbc7046-a460-4fb2-98f5-bfecbec82590.png)
получилось примерно такое:
![Screenshot from 2021-07-29 19-02-11](https://user-images.githubusercontent.com/51824674/127499536-e3dc2f02-2b37-48a2-953f-ef171fca1901.png)

2. Подключить/написать плагин для рейтинга. У слайдера с картинками переключать слайды при нажатии на соответствующую точку.
![plugin](https://user-images.githubusercontent.com/51824674/127499670-115d9a57-7465-469e-a05a-5436ade0a6de.png)
![Screenshot from 2021-07-29 19-23-54](https://user-images.githubusercontent.com/51824674/127499852-3cd1e73e-79a1-430c-855c-9f1e5baa9c8c.png)

**Comment by DmitrijMTP** [comment]
Можешь закрывать это issue
