### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by iatsdotfatr** [MadGoby/Task-2#4]
Использование миксов запрещено стандартами.
![mixes](https://user-images.githubusercontent.com/51824674/126662850-ada1a841-7fcc-4493-b037-2434eb887cb9.png)

**Comment by DmitrijMTP** [comment]
Если это модификатор ключ_значение, то именование не верное [вот тут есть примеры](https://ru.bem.info/methodology/quick-start/#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80)
![2021-08-30_18-18](https://user-images.githubusercontent.com/85491485/131362753-bf501ece-75d3-4db7-a183-a3b77671a6fd.png)
И такое не только здесь, пройдись плиз просмотри остальные блоки на именование модификаторов

Лучше избегать сокращений, кроме общепринятых. Это касается не только классов, но и в том числе блок "nav", например
![2021-08-30_18-28](https://user-images.githubusercontent.com/85491485/131364113-c1243921-14ce-41b4-a250-88ce868948ca.png)

**Comment by DmitrijMTP** [comment]
Можно закрывать
