### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by iatsdotfatr** [MadGoby/Task-2#5]
1. При ненулевых значениях всегда должна появляться кнопка "очистить".
![init](https://user-images.githubusercontent.com/51824674/126663222-13bb3384-cb22-406c-93de-8864bd95e863.png)

2. Кнопка "очистить" календаря должна убирать выделение дат.
![Screenshot from 2021-07-22 21-11-39](https://user-images.githubusercontent.com/51824674/126663381-f7ecb0bf-01f7-4832-801b-916761bfaa4b.png)

**Comment by iatsdotfatr** [comment]
1. Проверить календарь на соответствие макету.

2. Проверить работу дропдаунов в ui-kit. Окончания при изменении количества тоже изменять, нулевые значения не показывать.
![ontoggle](https://user-images.githubusercontent.com/51824674/127500603-3036b57f-54ba-4080-96fa-faa6e9c852ce.png)
![Screenshot from 2021-07-29 17-50-08](https://user-images.githubusercontent.com/51824674/127500638-5a6c0e86-41d9-4954-88ff-d62a4784dd2e.png)

3. Состояние кнопок изменять на hover. Проверить шрифт слайдера.
![Screenshot from 2021-07-29 17-45-12](https://user-images.githubusercontent.com/51824674/127500963-82de800f-f3cb-401e-b938-b2ac71f84f3a.png)

4. Переключать цвет у радиокнопок.
![color](https://user-images.githubusercontent.com/51824674/127501044-635c2f5e-1240-430d-a188-b364e7b8337a.png)

5. Также менять цвет ссылок при наведении. При на ссылки-дропдауны не должно происходить перехода по ссылке.
![dropdowns](https://user-images.githubusercontent.com/51824674/127501425-c88eaf44-8195-48d3-9765-099470e6ceb7.png)

6. При ширине экрана 768px менять футер на соответствующий из ui-kit, меню прятать в гамбургер. Как минимум до ширины 320px на страницах не должно быть горизонтального скролла.
![7801](https://user-images.githubusercontent.com/51824674/127501719-7e235304-b505-490b-85ae-a8e68fed58a8.png)
![Screenshot from 2021-07-29 19-27-01](https://user-images.githubusercontent.com/51824674/127501757-a98db82a-c9d9-4676-be9a-370bebdfd219.png)

**Comment by DmitrijMTP** [comment]
Можно закрывать
